env:
  global:
    - REPO="ionicapp"
    - CI_HOME=`pwd`/$REPO

language: node_js

install:
  - npm install -g ionic@beta
  - npm install -g cordova
  - npm install -g firebase-tools
script:
  - cd ionicapp
  - npm install
  - ionic build browser
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
