env:
  global:
    - REPO="ionicapp"
    - CI_HOME=`pwd`/$REPO

language: node_js

script:
  - cd ionicapp
  - echo 'Hello Firebase'
install:
  - npm install -g firebase-tools
after_success:
  - firebase login
